name: Continuous Integration Pipeline

on:
  push:
    branches:
      - master
      - feature/**
      - hotfix/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pruebas de SAST
        run: echo "Ejecución de pruebas de SAST"

      - name: Create credentials file
        run: |
          echo "[credentials]" > credentials.ini
          echo "username=${{ secrets.USERNAME }}" >> credentials.ini
          echo "password=${{ secrets.PASSWORD }}" >> credentials.ini

      - name: Build docker image
        run: |
          docker build -t devops_ws . --tag devops_ws:${{ github.run_number }}
        

