name: Pull Request Analysis

on:
  pull_request:
    branches:
      - master

jobs:
  analyze_and_decide:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Realizando análisis de SAST
        run: echo "Realizando análisis de SAST"

      - name: Comprobar requisitos del Pull Request
        id: check_file
        run: |
          if [ -f "allow_pull_request.txt" ]; then
            echo "Archivo allow_pull_request.txt encontrado. Permitiendo Pull Request."
            echo "::set-output name=ALLOW_PULL::true"
          else
            echo "Archivo allow_pull_request.txt no encontrado. Impidiendo Pull Request."
            echo "::set-output name=ALLOW_PULL::false"
          fi

      - name: Permitir Pull Request
        if: steps.check_file.outputs.ALLOW_PULL == 'true'
        run: echo "Permitiendo Pull Request"

      - name: Impedir Pull Request
        if: steps.check_file.outputs.ALLOW_PULL == 'false'
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1
